title: Fazzie's Homepage
page-top-title: Qianli Ma
top-section-bg-text: AGI Rock Musician
top-section-bg-sub-text: Building the next generation of AGI systems
home-subtitle: Qianli Ma&ensp;|&ensp;马千里
copyright-text: '&copy; Qianli Ma 2023-2024. All Rights Reserved.'
